// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportsStore.Infrastructure.Data;

#nullable disable

namespace SportsStore.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251121073401_AddProductIsFeatured")]
    partial class AddProductIsFeatured
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SportsStore.Domain.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            Name = "Bóng đá"
                        },
                        new
                        {
                            CategoryID = 2,
                            Name = "Quần áo"
                        },
                        new
                        {
                            CategoryID = 3,
                            Name = "Cầu lông"
                        },
                        new
                        {
                            CategoryID = 4,
                            Name = "Giày"
                        },
                        new
                        {
                            CategoryID = 5,
                            Name = "Bóng chuyền"
                        });
                });

            modelBuilder.Entity("SportsStore.Domain.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductID");

                    b.HasIndex("Category");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            Category = "Bóng đá",
                            CategoryId = 1,
                            Description = "Bóng đá dùng cho mọi loại sân, độ bền cao.",
                            IsFeatured = false,
                            Name = "Bóng đá Adidas",
                            Price = 25.00m
                        },
                        new
                        {
                            ProductID = 2,
                            Category = "Quần áo",
                            CategoryId = 2,
                            Description = "Áo đấu chất liệu thoáng khí, thấm hút mồ hôi.",
                            IsFeatured = false,
                            Name = "Áo đấu đội tuyển A",
                            Price = 49.99m
                        },
                        new
                        {
                            ProductID = 3,
                            Category = "Cầu lông",
                            CategoryId = 3,
                            Description = "Vợt nhẹ, cân bằng tốt, phù hợp cho người chơi trung cấp.",
                            IsFeatured = false,
                            Name = "Vợt cầu lông Yonex",
                            Price = 120.00m
                        },
                        new
                        {
                            ProductID = 4,
                            Category = "Giày",
                            CategoryId = 4,
                            Description = "Giày êm ái, hỗ trợ tối đa cho các buổi tập dài.",
                            IsFeatured = false,
                            Name = "Giày chạy bộ Nike Air",
                            Price = 95.00m
                        },
                        new
                        {
                            ProductID = 5,
                            Category = "Bóng chuyền",
                            CategoryId = 5,
                            Description = "Bóng chuyền tiêu chuẩn thi đấu quốc tế.",
                            IsFeatured = false,
                            Name = "Bóng chuyền Mikasa MVA200",
                            Price = 30.00m
                        },
                        new
                        {
                            ProductID = 6,
                            Category = "Bóng đá",
                            CategoryId = 1,
                            Description = "Bóng đá tập luyện chất lượng cao.",
                            IsFeatured = false,
                            Name = "Bóng đá Nike Strike",
                            Price = 20.00m
                        },
                        new
                        {
                            ProductID = 7,
                            Category = "Quần áo",
                            CategoryId = 2,
                            Description = "Quần short co giãn, thoải mái khi vận động.",
                            IsFeatured = false,
                            Name = "Quần short thể thao",
                            Price = 25.00m
                        });
                });

            modelBuilder.Entity("SportsStore.Domain.Models.Product", b =>
                {
                    b.HasOne("SportsStore.Domain.Models.Category", "CategoryRef")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryRef");
                });
#pragma warning restore 612, 618
        }
    }
}
